packageExtensions:
  babel-jest@*:
    dependencies:
      "@babel/core": "*"
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpFallbackMode: none

yarnPath: .yarn/releases/yarn-3.0.2.cjs
