packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
  styled-jsx@*:
    dependencies:
      "@babel/core": "*"
  babel-jest@*:
    dependencies:
      "@babel/core": "*"

pnpFallbackMode: none

yarnPath: .yarn/releases/yarn-3.0.1.cjs
