packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
  "@theme-ui/css@*":
    dependencies:
      react: "*"
  styled-jsx@*:
    dependencies:
      "@babel/core": "*"
  "node-fetch@2.6.1":
    peerDependencies:
      encoding: "*"
    peerDependenciesMeta:
      encoding:
        optional: true


yarnPath: .yarn/releases/yarn-3.0.0.cjs
