title: Dalton Craven
email: daltonjcraven@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The digital home of Dalton Craven, high school student and up-and-coming developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  cravend
repository: cravend/cravend.github.io
# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata

collections:
  projects:
    output: true
    permalink: /work/:name

defaults:
  -
    scope:
      path: "_projects"
    values:
      layout: "project"
