import { Locale, dir } from "@/lib/i18n/setup";
// import "./globals.css";
import { Atkinson_Hyperlegible } from "next/font/google";

const atkinsonHyperlegible = Atkinson_Hyperlegible({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  fallback: ["Arial"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  return (
    <html lang={params.lang} dir={dir[params.lang]}>
      <body className={atkinsonHyperlegible.className}>{children}</body>
    </html>
  );
}
